title: Lesson 24.02
description: Lesson 24.02: a starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://guinea-pigg.github.io/lesson2402

aux_links:
  Template Repository: https://github.com/guinea-pigg/lesson2402
